# .github/workflows/deploy.yml
name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write .env variables
        run: |
          echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> .env
          echo "ANTHROPIC_KEY=${{ secrets.ANTHROPIC_KEY }}" >> .env
          echo "TEST_GUILD_ID=${{ secrets.TEST_GUILD_ID }}" >> .env

      - name: Docker Compose Up
        run: |
          docker compose down
          docker compose up -d --build
